import React from 'react'

export const Cart = () => {
  return (
    <div>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        <br/>
        <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci rerum, repellat nisi quos suscipit iste unde necessitatibus fugiat rem error provident sunt deleniti eaque labore inventore explicabo dolores earum molestiae? Dignissimos sit voluptatibus molestias aliquid veniam fuga debitis maxime dolorum corporis beatae eum porro sed, ab alias perferendis. Exercitationem dolor repudiandae natus libero atque architecto fugiat eveniet? Tempore enim porro ut sequi ab, natus facilis aut doloribus in asperiores animi? Id at velit facere nobis quaerat quia, recusandae soluta ut quasi dolorem suscipit et modi repellendus vitae. Cum natus odio harum eos fuga iure excepturi officiis, earum accusantium qui recusandae.</div>
        
        

    </div>
  )
}
